# Classification of Iris flowers using K-nearest neighbours algorithm 

In [3]:
# import iris data set 
from sklearn.datasets import load_iris

In [4]:
iris = load_iris()
type(iris)

sklearn.datasets.base.Bunch

In [7]:
# print iris data 
print(iris.data[0:10,:])

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]]


In [4]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [5]:
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [6]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [7]:
print(type(iris.data))
print(type(iris.target))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [8]:
print(iris.target.shape)

(150,)


In [9]:
print(iris.data.shape)

(150, 4)


In [10]:
# store feature matrix in "X"

X = iris.data

# store RESPONSE vector in "Y"

y = iris.target

# scikit-learn 4-step modeling pattern 

<strong>Step-1: </strong> Import the class you plan to use 



In [11]:
from sklearn.neighbors import KNeighborsClassifier 

<strong>Step-2: </strong> Instantiate the 'estimator'

In [12]:
knn = KNeighborsClassifier(n_neighbors = 1)

In [13]:
print(knn)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')


<strong>Step-3: </strong> Fit the model with data(aka "model training")

1.Model is learning the relationship between X and y

2.Occurs in-place 

In [14]:
knn.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

<strong>Step-4: </strong> Predict the response for a new observation 


In [20]:
knn.predict([3,5,4,2])

C:\Users\Faraz\Anaconda3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([2])

In [21]:
X_new = ([3,5,4,2],[5,4,3,2])
knn.predict(X_new)

array([2, 1])

# Using a different value for K 

In [23]:
# instantiate the model using K = 5 

knn = KNeighborsClassifier(n_neighbors =5)


# fit the model with data 
knn.fit(X,y)

#predict the response for new observations 
knn.predict(X_new)

array([1, 1])

# Using Logistic Regression  

In [25]:
# import the class 

from sklearn.linear_model import LogisticRegression 

#instantiate the model (using default parameters)

logreg = LogisticRegression()

# fit the model with data 

logreg.fit(X,y)

#predict the response for new observation 

logreg.predict(X_new)

array([2, 0])